export enum Profession {
  Accountant = 'Accountant',
  Actor = 'Actor',
  Arhitect = 'Arhitect',
  Artist = 'Artist',
  Banker = 'Banker',
  Bartender = 'Bartender',
  Builder = 'Builder',
  Businessman = 'Businessman',
  Cashier = 'Cashier',
  Chef = 'Chef',
  Coach = 'Coach',
  Dentist = 'Dentist',
  Developer = 'Developer',
  Dietician = 'Dietician',
  Doctor = 'Doctor',
  Designer = 'Designer',
  Econimist = 'Econimist',
  Electrician = 'Electrician',
  Engineer = 'Engineer',
  Farmer = 'Farmer',
  Florist = 'Florist',
  Journalist = 'Journalist',
}
